# V2_digit_simulation.R
# NPKDC-vd classification on handwritten digits — two experiments:
#   Exp A: UCI Optical Recognition 8x8  (d=64,  B=1000 replications)
#   Exp B: MNIST 28x28                  (d=784, B=1000 replications)
#
# Protocol: 100 train + 100 test per digit-class, balanced, without replacement.
# Pre-screening (Exp B only): pixels with ANOVA F < 2 or mean intensity < 0.01
#   are removed before applying Silverman KDE.
#
# Data files (generated by fetch_openml via Python/sklearn):
#   /tmp/digits8_X.bin, /tmp/digits8_y.bin  — UCI optdigits n=5620, d=64
#   /tmp/mnist_X.bin,   /tmp/mnist_y.bin    — MNIST n=70000, d=784
#
# Outputs:
#   V2_digit_results.rds  (both experiments combined)
#   Printed LaTeX table row for each experiment

DATA_DIR <- file.path("..", "data")
library(parallel)

N_TR  <- 100L
N_TE  <- 100L
B     <- 1000L
C     <- 10L    # digit classes 0-9

# ============================================================
# Helpers
# ============================================================
bw_silverman <- function(x) {
  s <- sd(x); if (s < 1e-12) return(1e-4)
  1.06 * s * length(x)^(-0.2)
}

# Vectorised log-KDE for all test points vs one class (BLAS dgemm path)
log_kde_all <- function(X_te, X_tr, bw) {
  inv_h <- 1.0 / bw
  Ate   <- sweep(X_te, 2L, inv_h, `*`)
  Atr   <- sweep(X_tr, 2L, inv_h, `*`)
  a2    <- rowSums(Ate^2)
  b2    <- rowSums(Atr^2)
  ab    <- tcrossprod(Ate, Atr)
  D2    <- pmax(outer(a2, b2, `+`) - 2.0 * ab, 0.0)
  D     <- length(bw)
  cst   <- -0.5 * D * log(2 * pi) - sum(log(bw))
  lK    <- -0.5 * D2 + cst
  rmax  <- apply(lK, 1L, max)
  log(rowSums(exp(lK - rmax))) + rmax - log(nrow(X_tr))
}

# One balanced train/test split → classify → return (acc, prec, spec)
one_rep <- function(b, X_act, class_idx) {
  set.seed(b * 997L + 13L)
  splits <- lapply(class_idx, function(idx)
    sample(idx, N_TR + N_TE, replace = FALSE))
  X_tr <- do.call(rbind, lapply(splits, function(s) X_act[s[1:N_TR],      , drop=FALSE]))
  X_te <- do.call(rbind, lapply(splits, function(s) X_act[s[N_TR + 1:N_TE], , drop=FALSE]))
  y_tr <- rep(0:9, each = N_TR)
  y_te <- rep(0:9, each = N_TE)

  bw_list <- lapply(0:9, function(k)
    apply(X_tr[y_tr == k, , drop=FALSE], 2L, bw_silverman))

  n_te <- nrow(X_te)
  ld   <- matrix(0.0, n_te, C)
  for (k in seq_len(C))
    ld[, k] <- log_kde_all(X_te, X_tr[y_tr == k - 1L, , drop=FALSE], bw_list[[k]])

  y_hat <- apply(ld, 1L, which.max) - 1L
  acc   <- mean(y_hat == y_te)
  pv    <- sv <- numeric(C)
  for (k in 0:9) {
    tp <- sum(y_hat == k & y_te == k); fp <- sum(y_hat == k & y_te != k)
    tn <- sum(y_hat != k & y_te != k)
    pv[k+1L] <- if (tp+fp > 0) tp/(tp+fp) else 1.0
    sv[k+1L] <- if (tn+fp > 0) tn/(tn+fp) else 1.0
  }
  c(acc = acc, prec = mean(pv), spec = mean(sv))
}

run_experiment <- function(label, X_act, class_idx, n_cores) {
  cat(sprintf("\n=== %s: d=%d, B=%d, %d cores ===\n",
              label, ncol(X_act), B, n_cores))
  t0  <- proc.time()
  res <- mclapply(seq_len(B),
                  function(b) one_rep(b, X_act, class_idx),
                  mc.cores = n_cores)
  cat(sprintf("Elapsed: %.1f sec\n", (proc.time() - t0)["elapsed"]))
  mat <- do.call(rbind, res)
  smry <- function(v) sprintf("%.4f (%.4f)", mean(v), sd(v))
  cat("  Accuracy    :", smry(mat[,"acc"]),  "\n")
  cat("  Precision   :", smry(mat[,"prec"]), "\n")
  cat("  Specificity :", smry(mat[,"spec"]), "\n")
  list(mat     = mat,
       acc_mn  = mean(mat[,"acc"]),  acc_sd  = sd(mat[,"acc"]),
       prec_mn = mean(mat[,"prec"]), prec_sd = sd(mat[,"prec"]),
       spec_mn = mean(mat[,"spec"]), spec_sd = sd(mat[,"spec"]))
}

n_cores <- max(1L, detectCores() - 1L)
cat(sprintf("Using %d cores\n", n_cores))

# ============================================================
# Experiment A: UCI 8x8  (d = 64, n_total = 5620)
# ============================================================
cat("\nLoading UCI optdigits 8x8...\n")
nA <- 5620L; dA <- 64L
XA <- matrix(readBin("/tmp/digits8_X.bin", "numeric", nA*dA, size=4L, endian="little"),
             nrow=nA, ncol=dA, byrow=TRUE)
XA <- XA / 16.0   # normalise to [0,1]
yA <- readBin("/tmp/digits8_y.bin", "integer", nA, size=4L, endian="little")
class_idxA <- lapply(0:9, function(k) which(yA == k))
cat("Class sizes:", sapply(class_idxA, length), "\n")

set.seed(20260515)
resA <- run_experiment("Exp A: UCI 8x8", XA, class_idxA, n_cores)

# ============================================================
# Experiment B: MNIST 28x28 (d = 784 → pre-screen → d_active)
# ============================================================
cat("\nLoading MNIST 28x28...\n")
nB <- 70000L; dB <- 784L
XB_full <- matrix(readBin("/tmp/mnist_X.bin", "numeric", nB*dB, size=4L, endian="little"),
                  nrow=nB, ncol=dB, byrow=TRUE)
XB_full <- XB_full / 255.0
yB <- readBin("/tmp/mnist_y.bin", "integer", nB, size=4L, endian="little")
class_idxB <- lapply(0:9, function(k) which(yB == k))

# Pre-screening: ANOVA F > 2 AND mean intensity > 0.01
cat("Pre-screening pixels...\n")
set.seed(1L)
screen_n   <- 300L
screen_idx <- lapply(class_idxB, function(idx) sample(idx, screen_n))
Xsc <- do.call(rbind, lapply(screen_idx, function(idx) XB_full[idx,]))
ysc <- rep(0:9, each = screen_n); Nsc <- nrow(Xsc)
grand_mean  <- colMeans(Xsc)
class_means <- do.call(rbind, lapply(0:9, function(k)
  colMeans(Xsc[ysc == k,, drop=FALSE])))
SS_B <- colSums((class_means - matrix(grand_mean, C, dB, byrow=TRUE))^2) * screen_n
SS_W <- colSums(Xsc^2) - colSums(class_means^2) * screen_n
F_stat <- (SS_B / (C-1)) / pmax(SS_W / (Nsc-C), 1e-12)
active  <- which(F_stat > 2 & colMeans(Xsc) > 0.01)
XB      <- XB_full[, active, drop=FALSE]
cat(sprintf("Active pixels: %d / %d\n", length(active), dB))

set.seed(20260515)
resB <- run_experiment("Exp B: MNIST 28x28", XB, class_idxB, n_cores)

# ============================================================
# Save & print LaTeX rows
# ============================================================
V2 <- list(
  B = B, N_TR = N_TR, N_TE = N_TE,
  expA = c(resA, list(D=dA, label="UCI 8x8")),
  expB = c(resB, list(D=length(active), D_full=dB, active_pixels=active,
                      label="MNIST 28x28"))
)
saveRDS(V2, file.path(DATA_DIR, "V2_digit_results.rds"))
cat("\nSaved V2_digit_results.rds\n")

cat("\n=== LaTeX table rows ===\n")
fmt <- function(r) sprintf("%.4f (%.4f) & %.4f (%.4f) & %.4f (%.4f)",
                           r$acc_mn, r$acc_sd, r$prec_mn, r$prec_sd,
                           r$spec_mn, r$spec_sd)
cat(sprintf("UCI $8\\times8$   ($d=64$)            & %s \\\\\n", fmt(resA)))
cat(sprintf("MNIST $28\\times28$ ($d_{\\rm act}=%d$) & %s \\\\\n",
            length(active), fmt(resB)))
